# Generated by Django 4.2.7 on 2023-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
