# Generated by Django 4.2.7 on 2023-11-04 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_patient_address_patient_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.CharField(choices=[('ortho', 'ORTHO'), ('derma', 'DERMA'), ('gm', 'GM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_records',
            name='department',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='base.department'),
        ),
        migrations.AlterField(
            model_name='patient_records',
            name='diagnostics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient_records',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient_records',
            name='treatments',
            field=models.TextField(blank=True),
        ),
    ]
